"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowDownToLine, CornerDownLeft, CornerDownRight, Play, RotateCcw, Sparkles, Zap } from "lucide-react";
import { executeCommand, missionAchieved } from "./CommandExecutionEngine";
import { MissionGenerator } from "./MissionGenerator";
import { scoreRobotMission } from "./ScoringEngine";
import { robotSound } from "./SoundManager";
import type { Command, Direction, Point, RobotMissionMetrics } from "./Types";
import "./robot-mission.css";

const icons: Record<Command, any> = { FORWARD: ArrowDownToLine, LEFT: CornerDownLeft, RIGHT: CornerDownRight, COLLECT: Sparkles, ACTIVATE: Zap };
export default function RobotMissionGame({ disabled = false, sound = true, durationSeconds = 120, onComplete }: { disabled?: boolean; sound?: boolean; durationSeconds?: number; onComplete: (metrics: RobotMissionMetrics) => void }) {
  const [seconds, setSeconds] = useState(durationSeconds); const [missionIndex, setMissionIndex] = useState(0); const mission = MissionGenerator.get(missionIndex);
  const [position, setPosition] = useState<Point>(mission.start); const [direction, setDirection] = useState<Direction>(mission.direction); const [commands, setCommands] = useState<Command[]>([]); const [executing, setExecuting] = useState(false); const [collected, setCollected] = useState(false); const [activated, setActivated] = useState(false);
  const startedAt = useRef(new Date()); const missionStartedAt = useRef(Date.now()); const raw = useRef({ missionsStarted: 1, missionsCompleted: 0, commandsSelected: 0, commandsExecuted: 0, usefulCommands: 0, successfulMissions: 0, unsuccessfulMissions: 0, longestSuccessfulSequence: 0, highestDifficulty: 1, buildTimes: [] as number[], missionTimes: [] as number[] }); const finished = useRef(false);
  const finish = () => { if (finished.current) return; finished.current = true; const r = raw.current, scores = scoreRobotMission(r); const now = new Date(); onComplete({ age_group: "5–7 Years", missions_started: r.missionsStarted, missions_completed: r.missionsCompleted, commands_selected: r.commandsSelected, commands_executed: r.commandsExecuted, successful_missions: r.successfulMissions, unsuccessful_missions: r.unsuccessfulMissions, sequence_length_average: r.missionsCompleted ? r.commandsExecuted / r.missionsCompleted : 0, longest_successful_sequence: r.longestSuccessfulSequence, sequence_accuracy: scores.sequenceAccuracy, command_efficiency: scores.commandEfficiency, average_sequence_build_time: r.buildTimes.length ? r.buildTimes.reduce((a,b)=>a+b,0)/r.buildTimes.length : 0, average_mission_completion_time: r.missionTimes.length ? r.missionTimes.reduce((a,b)=>a+b,0)/r.missionTimes.length : 0, highest_difficulty: r.highestDifficulty, computational_thinking_score: scores.computationalThinkingScore, algorithmic_reasoning_score: scores.algorithmicReasoningScore, completion_percentage: Math.min(100, r.missionsCompleted / MissionGenerator.count * 100), overall_score: scores.overallScore, started_at: startedAt.current.toISOString(), completed_at: now.toISOString() }); };
  useEffect(() => { if (disabled) return; const id = window.setInterval(() => setSeconds(value => { if (value <= 1) { window.clearInterval(id); finish(); return 0; } return value - 1; }), 1000); return () => window.clearInterval(id); }, [disabled]);
  useEffect(() => { setPosition(mission.start); setDirection(mission.direction); setCommands([]); setCollected(false); setActivated(false); missionStartedAt.current = Date.now(); }, [missionIndex]);
  const available = useMemo<Command[]>(() => ["FORWARD", "LEFT", "RIGHT", ...(mission.object ? ["COLLECT" as Command] : []), ...(mission.station ? ["ACTIVATE" as Command] : [])], [mission]);
  const add = (command: Command) => { if (disabled || executing || commands.length >= mission.maxCommands) return; robotSound("select", sound); raw.current.commandsSelected++; setCommands(list => [...list, command]); };
  const run = async () => { if (!commands.length || executing || disabled) return; setExecuting(true); raw.current.buildTimes.push((Date.now() - missionStartedAt.current) / 1000); let p = position, d = direction, c = collected, a = activated, useful = 0; for (const command of commands) { const before = `${p.x}:${p.y}:${d}:${c}:${a}`; const next = executeCommand(p, d, command, mission, c, a); p = next.position; d = next.direction; c = next.collected; a = next.activated; if (`${p.x}:${p.y}:${d}:${c}:${a}` !== before) useful++; raw.current.commandsExecuted++; robotSound(command === "FORWARD" ? "move" : command === "LEFT" || command === "RIGHT" ? "turn" : "action", sound); setPosition(p); setDirection(d); setCollected(c); setActivated(a); await new Promise(resolve => window.setTimeout(resolve, 420)); } const success = missionAchieved(mission, p, c, a); raw.current.usefulCommands += useful; raw.current.missionsCompleted++; raw.current.missionTimes.push((Date.now() - missionStartedAt.current) / 1000); raw.current.highestDifficulty = Math.max(raw.current.highestDifficulty, mission.level); if (success) { raw.current.successfulMissions++; raw.current.longestSuccessfulSequence = Math.max(raw.current.longestSuccessfulSequence, commands.length); } else raw.current.unsuccessfulMissions++; await new Promise(resolve => window.setTimeout(resolve, 500)); if (missionIndex + 1 >= MissionGenerator.count) finish(); else { raw.current.missionsStarted++; setMissionIndex(value => value + 1); setExecuting(false); } };
  return <div className="robot-mission"><div className="rm-top"><div className="rm-level">{Array.from({length:7},(_,i)=><i key={i} className={i<=missionIndex?"on":""}/>)}</div><div className="rm-clock">{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,"0")}</div></div><div className="rm-world">{Array.from({length:28},(_,i)=>{ const x=i%7,y=Math.floor(i/7), obstacle=mission.obstacles.some(o=>o.x===x&&o.y===y); return <div key={i} className={`rm-cell ${obstacle?"obstacle":""}`}>{mission.target.x===x&&mission.target.y===y&&<span className="target"/>}{mission.object?.x===x&&mission.object.y===y&&!collected&&<Sparkles className="object"/>}{mission.station?.x===x&&mission.station.y===y&&!activated&&<Zap className="station"/>}{position.x===x&&position.y===y&&<span className="robot" style={{transform:`rotate(${direction*90}deg)`}}><b/><i/></span>}</div>})}</div><div className="rm-sequence">{Array.from({length:mission.maxCommands},(_,i)=>{const Icon=commands[i]?icons[commands[i]]:null;return <span key={i}>{Icon&&<Icon/>}</span>})}</div><div className="rm-controls"><div className="rm-commands">{available.map(command=>{const Icon=icons[command];return <button key={command} onClick={()=>add(command)} disabled={disabled||executing}><Icon/></button>})}<button onClick={()=>setCommands(list=>list.slice(0,-1))} disabled={disabled||executing||!commands.length}><RotateCcw/></button></div><button className="rm-run" onClick={run} disabled={disabled||executing||!commands.length}><Play fill="currentColor"/></button></div></div>;
}
