"use client";
import{useCallback,useEffect,useRef,useState}from"react";import{AnalyticsService}from"./AnalyticsService";import{DifficultyManager}from"./DifficultyManager";import{GameEngine}from"./GameEngine";import{MovementController}from"./MovementController";import{ParkingLayoutGenerator}from"./ParkingLayoutGenerator";import{SoundManager}from"./SoundManager";import{VehicleManager}from"./VehicleManager";import type{ParkingEscapeMetrics,ParkingLayout,ParkingRawMetrics}from"./Types";import"./ParkingEscapeGame.css";import"./MovementHints.css";import"./PremiumParking.css";
export const PARKING_ESCAPE_DURATION_SECONDS=120;
const fresh=():ParkingRawMetrics=>({age_group:"5–7 Years",levels_started:1,levels_completed:0,target_cars_escaped:0,total_vehicle_moves:0,efficient_moves:0,unnecessary_moves:0,highest_level:1,started_at:"",level_times:[],optimal_moves:0,invalid_moves:0});
export default function ParkingEscapeGame({disabled=false,sound=true,durationSeconds=PARKING_ESCAPE_DURATION_SECONDS,onComplete}:{disabled?:boolean;sound?:boolean;durationSeconds?:number;onComplete:(m:ParkingEscapeMetrics)=>void|Promise<void>}){
 const generator=useRef(new ParkingLayoutGenerator()),movement=useRef(new MovementController()),vehicles=useRef(new VehicleManager()),difficulty=useRef(new DifficultyManager()),sounds=useRef(new SoundManager(sound)),analytics=useRef(new AnalyticsService(onComplete));const metrics=useRef(fresh()),started=useRef(0),levelStarted=useRef(0),finished=useRef(false),board=useRef<HTMLDivElement>(null),drag=useRef<{id:string;sx:number;sy:number}|null>(null);
 const[layout,setLayout]=useState<ParkingLayout>(()=>new ParkingLayoutGenerator().generate(1)),[seconds,setSeconds]=useState(durationSeconds),[active,setActive]=useState<string|null>(null),[dragOffset,setDragOffset]=useState({x:0,y:0}),[moving,setMoving]=useState(false),[escaped,setEscaped]=useState(false),[result,setResult]=useState<ParkingEscapeMetrics|null>(null);
 useEffect(()=>{const time=Date.now();started.current=time;levelStarted.current=time;metrics.current.started_at=new Date(time).toISOString()},[]);useEffect(()=>sounds.current.setEnabled(sound),[sound]);useEffect(()=>{analytics.current=new AnalyticsService(onComplete)},[onComplete]);
 const finish=useCallback(async()=>{if(finished.current)return;finished.current=true;const output=new GameEngine().finish(metrics.current);setResult(output);await analytics.current.save(output)},[]);
 useEffect(()=>{const timer=window.setInterval(()=>{const left=Math.max(0,durationSeconds-Math.floor((Date.now()-started.current)/1000));setSeconds(left);if(left===0)void finish()},200);return()=>window.clearInterval(timer)},[durationSeconds,finish]);
 const completeLevel=async()=>{setEscaped(true);sounds.current.exit();metrics.current.levels_completed++;metrics.current.target_cars_escaped++;metrics.current.optimal_moves+=layout.optimalMoves;metrics.current.level_times.push((Date.now()-levelStarted.current)/1000);await new Promise(r=>window.setTimeout(r,900));if(finished.current)return;if(metrics.current.levels_completed>=4){await finish();return}const level=difficulty.current.next(metrics.current.levels_completed);metrics.current.levels_started++;metrics.current.highest_level=Math.max(metrics.current.highest_level,level);levelStarted.current=Date.now();setLayout(generator.current.generate(level));setEscaped(false)};
 const pointerDown=(id:string,e:React.PointerEvent)=>{if(disabled||finished.current||moving)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={id,sx:e.clientX,sy:e.clientY};setDragOffset({x:0,y:0});setActive(id)};
 const pointerMove=(e:React.PointerEvent)=>{const d=drag.current,v=layout.vehicles.find(item=>item.id===d?.id);if(!d||!v)return;setDragOffset(v.axis==="horizontal"?{x:e.clientX-d.sx,y:0}:{x:0,y:e.clientY-d.sy})};
 const pointerUp=(e:React.PointerEvent)=>{const d=drag.current,v=layout.vehicles.find(item=>item.id===d?.id),bounds=board.current?.getBoundingClientRect();drag.current=null;setActive(null);setDragOffset({x:0,y:0});if(!d||!v||!bounds)return;const cell=bounds.width/layout.cols,delta=Math.round((v.axis==="horizontal"?e.clientX-d.sx:e.clientY-d.sy)/cell);const resultMove=movement.current.move(layout,v.id,delta);if(!resultMove){if(Math.abs(delta)>0)metrics.current.invalid_moves++;return}metrics.current.total_vehicle_moves++;const useful=resultMove.escaped||resultMove.efficient;if(useful)metrics.current.efficient_moves++;else metrics.current.unnecessary_moves++;setMoving(true);setLayout(current=>vehicles.current.apply(current,resultMove));sounds.current.move();window.setTimeout(()=>{setMoving(false);sounds.current.park();if(resultMove.escaped)void completeLevel()},260)};
 return <main className="parking-escape"><div className="parking-skyline"><i/><i/><i/></div><header className="parking-hud"><div className="parking-level"><span>LEVEL</span><b>{layout.level}</b><i style={{width:`${layout.level/4*100}%`}}/></div><div className="parking-goal"><span className="target-mini"/> <b>TO EXIT</b><em>➜</em></div><div className="parking-timer">◷ <b>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,"0")}</b></div></header><section className="parking-world"><div className="parking-curb parking-curb-left"/><div className="parking-curb parking-curb-right"/><div className="parking-lamps"><i/><i/><i/></div><div ref={board} className="parking-grid" aria-label="Draggable parking area">{Array.from({length:36},(_,i)=><i className="parking-space" key={i}/>)}<div className="parking-exit"><span>EXIT</span><b>➜</b></div>{layout.vehicles.map(v=><button key={v.id} type="button" aria-label={v.target?"Target vehicle":"Parked vehicle"} className={`parking-car ${v.axis} ${v.target?"target":""} ${active===v.id?"active":""} ${escaped&&v.target?"escaping":""}`} style={{"--x":v.x,"--y":v.y,"--length":v.length,"--car":v.color,"--drag-x":`${active===v.id?dragOffset.x:0}px`,"--drag-y":`${active===v.id?dragOffset.y:0}px`} as React.CSSProperties} onPointerDown={e=>pointerDown(v.id,e)} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}><span className="car-glass"/><span className="car-light left"/><span className="car-light right"/><i/><i/>{v.target&&<b>★</b>}</button>)}</div><div className="parking-legend"><span className="target-mini"/><b>Guide the star car to the exit</b><i>Drag each vehicle along its lane</i></div><div className="parking-cones"><i/><i/><i/></div></section>{moving&&<div className="parking-dust"><i/><i/><i/></div>}{escaped&&<div className="parking-celebration"><i>✦</i><i>✦</i><i>✦</i></div>}{result&&<div className="parking-finish"><div><span>🏁</span><h2>Parking complete</h2><p>{result.levels_completed} cars escaped</p></div></div>}</main>
}
