export type DestinationColor = "blue" | "green" | "red";
export type GateId = "gateA" | "gateB" | "gateC" | "gateD";
export type PlaneState =
  "arriving" | "waiting" | "taxiing" | "holding" | "parked" | "departing";
export type Point = { x: number; y: number };
export type Plane = {
  id: string;
  x: number;
  y: number;
  destination: DestinationColor;
  symbol: "circle" | "star";
  state: PlaneState;
  priority: boolean;
  route: Point[];
  routeIndex: number;
  spawnedAt: number;
  decisionAt: number;
  assignedGate?: GateId;
  indicatorUntil: number;
  validRoute?: boolean;
  arrivalX: number;
  angle: number;
};
export type Gate = {
  id: GateId;
  x: number;
  y: number;
  color: DestinationColor;
  occupiedBy?: string;
  temporarilyClosed: boolean;
  releaseAt: number;
};
export type Level = {
  stage: number;
  gateCount: number;
  maxPlanes: number;
  arrivalMs: number;
  speed: number;
  priorityChance: number;
  closureChance: number;
  memoryComplexity: number;
};
export type RouteEvent = {
  kind: "route" | "complete" | "misroute" | "redirect" | "conflict";
  at: number;
  planeId: string;
  correct: boolean;
  decisionTime: number;
  priority: boolean;
  efficiency: number;
};
export type AirportMetrics = {
  sessionDuration: number;
  planesSpawned: number;
  planesCompleted: number;
  planesRouted: number;
  planesMisrouted: number;
  planesRedirected: number;
  gatesUsed: number;
  gateConflicts: number;
  routeConflicts: number;
  priorityPlanes: number;
  priorityPlanesHandled: number;
  gateClosures: number;
  gateClosureAdaptations: number;
  taskSwitches: number;
  taskSwitchLatency: number;
  abandonedTasks: number;
  recoveredTasks: number;
  destinationMemoryErrors: number;
  averageRouteEfficiency: number;
  unnecessaryRouteChanges: number;
  decisionTimes: number[];
  averageDecisionTime: number;
  beginningPerformance: number;
  middlePerformance: number;
  endingPerformance: number;
  highestDifficulty: number;
  planningScore: number;
  dividedAttentionScore: number;
  taskSwitchingScore: number;
  decisionMakingScore: number;
  workingMemoryScore: number;
  prioritizationScore: number;
  cognitiveFlexibilityScore: number;
  problemSolvingScore: number;
  sustainedAttentionScore: number;
  overallScore: number;
  completionStatus: string;
};
