export type Vec={x:number;y:number};
export type Rect=Vec&{w:number;h:number};
export type VaultItem={id:string;label:string;color:string;symbol:string;position:Vec;room:number;collected:boolean;delivered:boolean;encodedAt:number;previousRoom?:number};
export type VaultState={player:Vec;carrying:string|null;items:VaultItem[];round:number;phase:"ENCODING"|"PLAYING"|"UPDATING"|"DONE";phaseUntil:number;doors:{open:boolean;nextChange:number};robot:Vec;metrics:VaultMetrics;visited:Set<number>;lastRoom:number|null;wrongAttempts?:number;wrongRooms?:Set<number>};
export type VaultMetrics={correctDeliveries:number;incorrectDeliveries:number;recoveredDeliveries:number;abandonedItems:number;memoryConflicts:number;updatedMappings:number;staleMappingAttempts:number;memoryDelay:number;timeSinceEncoding:number;timeToDelivery:number;mappingChanges:number;mappingUpdateSuccess:number;mappingUpdateFailure:number;oldMappingAttempts:number;newMappingAttempts:number;updateLatency:number;distractionEvents:number;distractionDuringEncoding:number;distractionDuringNavigation:number;distractionDuringDelivery:number;distanceTravelled:number;roomsVisited:number;wrongRoomEntries:number;routeChanges:number;backtracking:number;navigationTime:number;deliveryTime:number;beginningPerformance:number;middlePerformance:number;endingPerformance:number;highestDifficulty:number;completionStatus:string};
export const WORLD={w:960,h:600};
export const ROOMS:Rect[]=[{x:24,y:24,w:250,h:170},{x:355,y:24,w:250,h:170},{x:686,y:24,w:250,h:170},{x:24,y:406,w:250,h:170},{x:355,y:406,w:250,h:170},{x:686,y:406,w:250,h:170}];
export const STATIONS:Rect[]=ROOMS.map(r=>({x:r.x+r.w/2-28,y:r.y+r.h/2-28,w:56,h:56}));
const WALLS:Rect[]=[{x:0,y:0,w:960,h:20},{x:0,y:580,w:960,h:20},{x:0,y:0,w:20,h:600},{x:940,y:0,w:20,h:600}];
const ITEMS=[['Azure Key','#38bdf8','◆'],['Emerald Cell','#34d399','⬡'],['Crimson Core','#fb7185','●'],['Amber Prism','#fbbf24','▲'],['Violet Chip','#a78bfa','■']] as const;
const rand=(seed:number)=>{let n=(Math.imul(seed|0,0x9e3779b1)^0x85ebca6b)>>>0;return()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296}};
export const difficultyFor=(round:number)=>Math.min(5,round+1);
export function roomAt(p:Vec){return ROOMS.findIndex(r=>p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h)+1||null}
export function generateItems(seed:number,round:number,previous:VaultItem[]=[]){const r=rand(seed+round*7919),count=Math.min(5,2+round),used=new Set<number>();return ITEMS.slice(0,count).map((d,i)=>{let room=1+Math.floor(r()*6);while(used.has(room))room=1+(room%6);used.add(room);const old=previous.find(x=>x.id===`item-${i}`);if(round>0&&i===0&&old&&room===old.room)room=room%6+1;return{id:`item-${i}`,label:d[0],color:d[1],symbol:d[2],position:{x:430+i*35,y:275+(i%2)*55},room,collected:false,delivered:false,encodedAt:0,previousRoom:old?.room}})}
export function createVault(seed=1,now=0):VaultState{return{player:{x:480,y:300},carrying:null,items:generateItems(seed,0),round:0,phase:"ENCODING",phaseUntil:now+6500,doors:{open:true,nextChange:now+9000},robot:{x:100,y:300},visited:new Set(),lastRoom:null,metrics:{correctDeliveries:0,incorrectDeliveries:0,recoveredDeliveries:0,abandonedItems:0,memoryConflicts:0,updatedMappings:0,staleMappingAttempts:0,memoryDelay:0,timeSinceEncoding:0,timeToDelivery:0,mappingChanges:0,mappingUpdateSuccess:0,mappingUpdateFailure:0,oldMappingAttempts:0,newMappingAttempts:0,updateLatency:0,distractionEvents:0,distractionDuringEncoding:0,distractionDuringNavigation:0,distractionDuringDelivery:0,distanceTravelled:0,roomsVisited:0,wrongRoomEntries:0,routeChanges:0,backtracking:0,navigationTime:0,deliveryTime:0,beginningPerformance:0,middlePerformance:0,endingPerformance:0,highestDifficulty:1,completionStatus:"COMPLETED"}}}
export function collides(p:Vec){return WALLS.some(w=>p.x< w.x+w.w&&p.x+18>w.x&&p.y<w.y+w.h&&p.y+18>w.y)}
export function movePlayer(s:VaultState,dx:number,dy:number,dt:number){if(s.phase!=="PLAYING")return;const length=Math.hypot(dx,dy)||1,speed=190,next={x:s.player.x+dx/length*speed*dt,y:s.player.y+dy/length*speed*dt};if(!collides(next)){s.metrics.distanceTravelled+=Math.hypot(next.x-s.player.x,next.y-s.player.y);s.player=next}const room=roomAt(s.player);if(room&&!s.visited.has(room)){s.visited.add(room);s.metrics.roomsVisited=s.visited.size}if(room!==s.lastRoom&&s.lastRoom!==null)s.metrics.routeChanges++;s.lastRoom=room}
export function nearbyItem(s:VaultState){return s.items.find(i=>!i.collected&&!i.delivered&&Math.hypot(i.position.x-s.player.x,i.position.y-s.player.y)<52)}
export function nearbyStation(s:VaultState){return STATIONS.findIndex(r=>Math.hypot(r.x+r.w/2-s.player.x,r.y+r.h/2-s.player.y)<70)+1||null}
export function nearbyCorrectStation(s:VaultState){if(!s.carrying)return false;const item=s.items.find(i=>i.id===s.carrying);return Boolean(item&&nearbyStation(s)===item.room)}
export function interact(s:VaultState,now:number){if(s.phase!=="PLAYING")return"none";if(!s.carrying){const item=nearbyItem(s);if(!item)return"none";item.collected=true;s.carrying=item.id;s.wrongAttempts=0;s.wrongRooms=new Set();return"pickup"}const item=s.items.find(i=>i.id===s.carrying)!;const attemptedRoom=nearbyStation(s);if(!attemptedRoom)return"none";if(attemptedRoom!==item.room){s.wrongRooms??=new Set();if(s.wrongRooms.has(attemptedRoom))return"wrong_station";s.wrongRooms.add(attemptedRoom);s.wrongAttempts=s.wrongRooms.size;s.metrics.incorrectDeliveries++;s.metrics.wrongRoomEntries++;if(item.previousRoom===attemptedRoom){s.metrics.staleMappingAttempts++;s.metrics.oldMappingAttempts++;s.metrics.memoryConflicts++}if(s.wrongAttempts>=3){const remaining=s.items.filter(i=>!i.delivered).length;s.metrics.abandonedItems+=remaining;s.metrics.mappingUpdateFailure+=item.previousRoom?1:0;s.items.forEach(i=>i.delivered=true);s.carrying=null;return"round_skipped"}return"wrong_station"}item.delivered=true;s.carrying=null;s.wrongAttempts=0;s.wrongRooms=new Set();s.metrics.correctDeliveries++;s.metrics.timeToDelivery+=now-item.encodedAt;s.metrics.memoryDelay+=now-item.encodedAt;if(item.previousRoom){s.metrics.mappingUpdateSuccess++;s.metrics.newMappingAttempts++;s.metrics.updateLatency+=now-item.encodedAt}return"delivered"}
export function updateVault(s:VaultState,seed:number,now:number){if(s.phase==="ENCODING"&&now>=s.phaseUntil){s.phase="PLAYING";s.items.forEach(i=>i.encodedAt=now)}if(now>=s.doors.nextChange){s.doors.open=!s.doors.open;s.doors.nextChange=now+9000;s.metrics.distractionEvents++;if(s.phase==="ENCODING")s.metrics.distractionDuringEncoding++;else if(s.carrying)s.metrics.distractionDuringDelivery++;else s.metrics.distractionDuringNavigation++}s.robot.x=80+((now/18)%800);if(s.phase==="PLAYING"&&s.items.every(i=>i.delivered)){const old=s.items;s.round++;s.metrics.highestDifficulty=difficultyFor(s.round);s.metrics.mappingChanges+=old.filter(i=>i.previousRoom!==undefined).length;s.items=generateItems(seed,s.round,old);s.metrics.updatedMappings+=s.items.filter(i=>i.previousRoom&&i.previousRoom!==i.room).length;s.phase="ENCODING";s.phaseUntil=now+Math.max(3500,6500-s.round*600)}}
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
export function scoreVault(m:VaultMetrics,items:VaultItem[],elapsed:number){const attempts=m.correctDeliveries+m.incorrectDeliveries,accuracy=attempts?m.correctDeliveries/attempts*100:0,updateTotal=m.mappingUpdateSuccess+m.mappingUpdateFailure,update=updateTotal?m.mappingUpdateSuccess/updateTotal*100:accuracy,retention=clamp(accuracy-m.staleMappingAttempts*5),spatial=clamp(70+m.roomsVisited*4-m.wrongRoomEntries*7),attention=clamp(86-m.distractionEvents*1.5-m.incorrectDeliveries*5),navigation=clamp(90-m.routeChanges*1.2-m.backtracking*3),working=clamp(retention*.48+update*.3+attention*.12+spatial*.1);return{...m,abandonedItems:items.filter(i=>!i.delivered).length,timeSinceEncoding:elapsed,informationRetentionScore:retention,spatialMemoryScore:spatial,memoryUpdatingScore:clamp(update),attentionScore:attention,sequencingScore:clamp(working*.94),recallUnderDistractionScore:clamp((retention+attention)/2),navigationScore:navigation,informationManagementScore:clamp((retention+update)/2),errorMonitoringScore:clamp(80-m.incorrectDeliveries*6+m.recoveredDeliveries*5),cognitiveLoadManagementScore:clamp((working+attention)/2),workingMemoryScore:working,memoryConsistency:retention,updatingConsistency:clamp(update),recallConsistency:clamp((working+retention)/2),beginningPerformance:working,middlePerformance:working,endingPerformance:working,overallScore:clamp(working*.65+spatial*.15+attention*.1+navigation*.1),sessionDuration:Math.round(elapsed/1000),completionStatus:m.completionStatus}}
export const timedOut=(seconds:number)=>seconds<=0;
export const completedThreeRounds=(round:number)=>round>=3;
export function keyVector(keys:Set<string>){return{x:Number(keys.has('ArrowRight')||keys.has('KeyD'))-Number(keys.has('ArrowLeft')||keys.has('KeyA')),y:Number(keys.has('ArrowDown')||keys.has('KeyS'))-Number(keys.has('ArrowUp')||keys.has('KeyW'))}}
