"use client";
/* eslint-disable react/no-unescaped-entities */
import{useCallback,useEffect,useRef,useState}from"react";
import{completedThreeRounds,createVault,interact,keyVector,nearbyCorrectStation,nearbyItem,ROOMS,scoreVault,STATIONS,updateVault,movePlayer,type VaultState}from"./Engine";
import"./MemoryVaultGame.css";
type Props={disabled?:boolean;remainingSeconds?:number;practiceOnly?:boolean;attemptSeed?:number;sound?:boolean;onComplete:(m:ReturnType<typeof scoreVault>)=>void|Promise<void>};
const fmt=(n:number)=>`${Math.floor(Math.max(0,n)/60)}:${String(Math.max(0,n)%60).padStart(2,"0")}`;
export default function MemoryVaultGame({disabled=false,remainingSeconds=180,practiceOnly=false,attemptSeed=1,onComplete}:Props){
 const canvas=useRef<HTMLCanvasElement>(null),raf=useRef(0),last=useRef(0),startedAt=useRef(0),done=useRef(false),keys=useRef(new Set<string>()),touch=useRef({x:0,y:0}),state=useRef<VaultState>(createVault(attemptSeed));
 const complete=useRef(onComplete),secondsRef=useRef(remainingSeconds);const[started,setStarted]=useState(false),[showHelp,setShowHelp]=useState(false),[seconds,setSeconds]=useState(remainingSeconds),[ui,setUi]=useState({phase:"ENCODING",carrying:"",delivered:0,prompt:""});
 useEffect(()=>{complete.current=onComplete},[onComplete]);useEffect(()=>{secondsRef.current=remainingSeconds},[remainingSeconds]);
 useEffect(()=>{if(!started)return;const now=performance.now();state.current=createVault(attemptSeed,now);state.current.phaseUntil=now+9000;startedAt.current=now;last.current=now},[attemptSeed,started]);
 const finish=useCallback((status="COMPLETED")=>{if(done.current)return;done.current=true;cancelAnimationFrame(raf.current);state.current.metrics.completionStatus=status;void complete.current(scoreVault(state.current.metrics,state.current.items,performance.now()-startedAt.current))},[]);
 useEffect(()=>{if(started&&!practiceOnly&&remainingSeconds<=0)finish("TIME_LIMIT_REACHED")},[finish,practiceOnly,remainingSeconds,started]);
 useEffect(()=>{if(!started||!practiceOnly||disabled)return;const id=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(id)},[disabled,practiceOnly,started]);
 useEffect(()=>{if(started&&practiceOnly&&seconds<=0)finish("TIME_LIMIT_REACHED")},[finish,practiceOnly,seconds,started]);
 useEffect(()=>{if(!started||disabled)return;const id=setInterval(()=>{if(completedThreeRounds(state.current.round))finish("COMPLETED")},100);return()=>clearInterval(id)},[disabled,finish,started]);
 useEffect(()=>{if(disabled||!started)return;const down=(e:KeyboardEvent)=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","KeyW","KeyA","KeyS","KeyD","KeyE","Space"].includes(e.code)){e.preventDefault();keys.current.add(e.code);if(e.code==="KeyE"||e.code==="Space")interact(state.current,performance.now())}},up=(e:KeyboardEvent)=>keys.current.delete(e.code),blur=()=>keys.current.clear();addEventListener("keydown",down);addEventListener("keyup",up);addEventListener("blur",blur);return()=>{removeEventListener("keydown",down);removeEventListener("keyup",up);removeEventListener("blur",blur)}},[disabled,started]);
 useEffect(()=>{if(!started||disabled)return;const c=canvas.current,ctx=c?.getContext("2d");if(!c||!ctx)return;last.current=startedAt.current=performance.now();let lastUi=0;const draw=(now:number)=>{const dt=Math.min(.05,(now-last.current)/1000);last.current=now;const v=keyVector(keys.current);movePlayer(state.current,v.x+touch.current.x,v.y+touch.current.y,dt);updateVault(state.current,attemptSeed,now);const s=state.current,w=c.width,h=c.height,scale=Math.min(w/960,h/600);ctx.setTransform(scale,0,0,scale,0,0);ctx.clearRect(0,0,960,600);ctx.fillStyle="#061525";ctx.fillRect(0,0,960,600);ctx.strokeStyle="#173c55";ctx.lineWidth=1;for(let x=0;x<960;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,600);ctx.stroke()}for(let y=0;y<600;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(960,y);ctx.stroke()}
 ROOMS.forEach((r,i)=>{const colors=["#0e3a55","#26305a","#16473f","#4a273e","#3f351b","#263d55"];ctx.fillStyle=colors[i];ctx.fillRect(r.x,r.y,r.w,r.h);ctx.strokeStyle=["#38bdf8","#818cf8","#34d399","#fb7185","#fbbf24","#67e8f9"][i];ctx.lineWidth=4;ctx.strokeRect(r.x,r.y,r.w,r.h);ctx.fillStyle="#dbeafe";ctx.font="700 16px sans-serif";ctx.fillText(`ROOM ${i+1}`,r.x+14,r.y+25);ctx.font="28px sans-serif";ctx.fillText(["◈","△","◎","✦","⬡","▣"][i],r.x+r.w-46,r.y+34)});
 ctx.fillStyle="#0b2136";ctx.fillRect(275,215,410,170);ctx.fillStyle=s.doors.open?"#22d3ee":"#ef476f";ctx.fillRect(465,194,30,22);ctx.fillRect(465,384,30,22);ctx.font="11px sans-serif";ctx.fillText(s.doors.open?"OPEN":"SEALED",505,210);
 STATIONS.forEach((r,i)=>{ctx.strokeStyle=["#38bdf8","#818cf8","#34d399","#fb7185","#fbbf24","#67e8f9"][i];ctx.lineWidth=3;ctx.strokeRect(r.x,r.y,r.w,r.h);ctx.fillStyle="rgba(255,255,255,.08)";ctx.fillRect(r.x,r.y,r.w,r.h)});
 s.items.forEach(item=>{if(item.collected||item.delivered)return;ctx.shadowColor=item.color;ctx.shadowBlur=16;ctx.fillStyle=item.color;ctx.beginPath();ctx.arc(item.position.x,item.position.y,14+Math.sin(now/250)*2,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#fff";ctx.font="bold 15px sans-serif";ctx.fillText(item.symbol,item.position.x-6,item.position.y+5)});
 ctx.fillStyle="#f59e0b";ctx.fillRect(s.robot.x,286,30,20);ctx.fillStyle="#fde68a";ctx.fillRect(s.robot.x+5,280,20,8);
 ctx.save();ctx.translate(s.player.x,s.player.y);ctx.fillStyle="#e2e8f0";ctx.beginPath();ctx.arc(0,-8,9,0,Math.PI*2);ctx.fill();ctx.fillStyle="#22d3ee";ctx.fillRect(-10,2,20,24);if(s.carrying){const item=s.items.find(i=>i.id===s.carrying)!;ctx.fillStyle=item.color;ctx.beginPath();ctx.arc(0,-28,9,0,Math.PI*2);ctx.fill()}ctx.restore();
 if(s.phase!=="PLAYING"){ctx.fillStyle="rgba(2,8,23,.9)";ctx.fillRect(190,125,580,350);ctx.fillStyle="#67e8f9";ctx.font="800 15px sans-serif";ctx.fillText(s.round?"VAULT ROUTES UPDATED":"VAULT ACCESS MANIFEST",350,165);ctx.fillStyle="#fff";ctx.font="900 28px sans-serif";ctx.fillText("Memorize each item destination",265,205);s.items.forEach((item,i)=>{ctx.fillStyle=item.color;ctx.font="bold 19px sans-serif";ctx.fillText(`${item.symbol}  ${item.label}`,275,255+i*42);ctx.fillStyle="#cbd5e1";ctx.fillText(`→  ROOM ${item.room}`,540,255+i*42)});ctx.fillStyle="#94a3b8";ctx.font="13px sans-serif";ctx.fillText("The manifest will seal. Find, carry and place each item yourself.",278,438)}
 if(now-lastUi>100){lastUi=now;const carry=s.carrying?s.items.find(i=>i.id===s.carrying)?.label||"":"";const prompt=nearbyItem(s)?"E / ACTION — COLLECT":nearbyCorrectStation(s)?"E / ACTION — PLACE":"";setUi({phase:s.phase,carrying:carry,delivered:s.metrics.correctDeliveries,prompt})}raf.current=requestAnimationFrame(draw)};raf.current=requestAnimationFrame(draw);return()=>cancelAnimationFrame(raf.current)},[attemptSeed,disabled,started]);
 // Event-handler factories only mutate the real-time input ref after a pointer event.
 // eslint-disable-next-line react-hooks/refs
 const press=(x:number,y:number)=>(e:React.PointerEvent<HTMLButtonElement>)=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);touch.current={x,y}},release=()=>touch.current={x:0,y:0};
 return <div className="memory-vault">{!started?<div className="vault-intro"><div><span>EASY 3-STEP ADVENTURE</span><h1>🧠 Memory Vault</h1><p className="vault-intro-lead">You will briefly see where each glowing item belongs. Remember the room number before the list disappears.</p><div className="vault-easy-steps"><div><b>1</b><strong>LOOK</strong><small>Remember item → room</small></div><div><b>2</b><strong>COLLECT</strong><small>Walk to an item and press ACTION</small></div><div><b>3</b><strong>DELIVER</strong><small>Go to that room's square and press ACTION</small></div></div><p className="vault-controls-note">Move with WASD, arrow keys, or arrow buttons.</p><button onClick={()=>setStarted(true)}>SHOW THE ITEM LIST</button></div></div>:<><canvas ref={canvas} width={960} height={600}/><div className="vault-hud"><b>{fmt(practiceOnly?seconds:remainingSeconds)}</b><span>{ui.carrying?`CARRYING: ${ui.carrying}`:"FIND A GLOWING ITEM"}</span><span>DELIVERED {ui.delivered}</span></div><button className="vault-help-button" onClick={()=>setShowHelp(true)}>HOW TO PLAY</button>{ui.phase==="PLAYING"&&<><div className="vault-task-guide"><span className={!ui.carrying?"active":"done"}>1 COLLECT</span><i>›</i><span className={ui.carrying?"active":""}>2 GO TO ROOM</span><i>›</i><span className={ui.carrying?"active":""}>3 ACTION</span></div><div className="vault-next-action">{ui.carrying?<><strong>You picked up {ui.carrying}.</strong><span>Move to its remembered room → stand on the large square → press ACTION.</span></>:<><strong>Walk to any glowing item.</strong><span>Stand next to it, then press ACTION to pick it up.</span></>}</div></>}{ui.prompt&&<div className="vault-prompt">{ui.prompt}</div>}<div className="vault-controls"><div><button aria-label="Move up" onPointerDown={press(0,-1)} onPointerUp={release} onPointerCancel={release}>▲</button><span><button aria-label="Move left" onPointerDown={press(-1,0)} onPointerUp={release} onPointerCancel={release}>◀</button><button aria-label="Move down" onPointerDown={press(0,1)} onPointerUp={release} onPointerCancel={release}>▼</button><button aria-label="Move right" onPointerDown={press(1,0)} onPointerUp={release} onPointerCancel={release}>▶</button></span></div><button className="vault-action" onPointerDown={()=>interact(state.current,performance.now())}>ACTION<small>E / SPACE</small></button></div>{showHelp&&<div className="vault-help"><div><h2>What do I do?</h2><p><b>1.</b> Move beside a glowing item and press ACTION.</p><p><b>2.</b> Move into the room you memorized.</p><p><b>3.</b> Stand on the large square inside that room.</p><p><b>4.</b> Press ACTION again to place the item.</p><small>This help does not reveal the hidden room answer.</small><button onClick={()=>setShowHelp(false)}>CONTINUE PLAYING</button></div></div>}</>}</div>
}
