export type RegisteredGame = {
  name: string;
  slug: string;
  description: string;
  category: string;
  ageGroup: string;
  difficulty: string;
  durationSeconds: number;
  thumbnail: string;
  componentName: string;
  gameType: string;
  templateCode: string;
  cognitiveSkill: string;
};

// Adding a game here is the only backend registration step. GamesService
// synchronizes this catalog into the master `games` table on application start.
// Every registered game must use one of the supported age-group labels.
export const GAME_CATALOG: RegisteredGame[] = [
  {
    name: 'Adventure Dash',
    slug: 'adventure-dash',
    description:
      'A real-time adventure game with responsive navigation and live interactions.',
    category: 'Adventure',
    ageGroup: '7–9 Years',
    difficulty: 'MEDIUM',
    durationSeconds: 900,
    thumbnail: '/games/adventure-dash.svg',
    componentName: 'ADVENTURE_GAME',
    gameType: 'ASSESSMENT_ENGINE',
    templateCode: 'GT-ADVENTURE',
    cognitiveSkill: 'Decision Making',
  },
  {
    name: 'Airport Controller — Planning, Divided Attention & Task Switching',
    slug: 'airport-controller',
    description:
      'A continuous airport-management assessment where children route moving planes, manage gates, prioritize traffic, and adapt to changing airport conditions.',
    category: 'Executive Function & Planning',
    ageGroup: '9–11 Years',
    difficulty: 'PROGRESSIVE',
    durationSeconds: 120,
    thumbnail: '/games/airport-controller.svg',
    componentName: 'AIRPORT_CONTROLLER',
    gameType: 'REAL_TIME',
    templateCode: 'GT-AIRPORT-CONTROLLER',
    cognitiveSkill: 'Planning',
  },
  {
    name: 'Balloon Popper',
    slug: 'balloon-popper',
    description: 'A fast real-time balloon interaction game.',
    category: 'Arcade',
    ageGroup: '4–5 Years',
    difficulty: 'MEDIUM',
    durationSeconds: 600,
    thumbnail: '/games/balloon-popper.svg',
    componentName: 'BALLOON_POP',
    gameType: 'ASSESSMENT_ENGINE',
    templateCode: 'GT-BALLOON',
    cognitiveSkill: 'Processing Speed',
  },
  {
    name: 'Ball Stack',
    slug: 'ball-stack',
    description:
      'A precision stacking assessment measuring hand-eye coordination, fine motor control, concentration, and timing.',
    category: 'Hand-Eye Coordination',
    ageGroup: '3–4 Years',
    difficulty: 'EASY',
    durationSeconds: 90,
    thumbnail: '/games/ball-stack.svg',
    componentName: 'BALL_STACK',
    gameType: 'REAL_TIME',
    templateCode: 'GT-BUILDING',
    cognitiveSkill: 'Hand-Eye Coordination & Fine Motor Skills',
  },
  {
    name: 'Color Path',
    slug: 'color-path',
    description:
      'A real-time cognitive assessment of visual recognition and observation through color-guided path choices.',
    category: 'Visual Recognition',
    ageGroup: '3–4 Years',
    difficulty: 'EASY',
    durationSeconds: 60,
    thumbnail: '/games/color-path.svg',
    componentName: 'COLOR_PATH',
    gameType: 'REAL_TIME',
    templateCode: 'GT-COLOR-PATH',
    cognitiveSkill: 'Visual Recognition & Observation',
  },
  {
    name: 'Magic Paint',
    slug: 'magic-paint',
    description:
      'A free-choice real-time creativity and cause-and-effect assessment using animated object coloring.',
    category: 'Creativity & Cause-and-Effect Assessment',
    ageGroup: '3–4 Years',
    difficulty: 'EASY',
    durationSeconds: 120,
    thumbnail: '/games/magic-paint.svg',
    componentName: 'MAGIC_PAINT',
    gameType: 'REAL_TIME',
    templateCode: 'GT-MAGIC-PAINT',
    cognitiveSkill: 'Creativity & Cause and Effect Understanding',
  },
  {
    name: 'Train Track Builder',
    slug: 'train-track-builder',
    description:
      'A real-time cognitive assessment of logical thinking and cause and effect through railway connection puzzles.',
    category: 'Logical Thinking',
    ageGroup: '4–5 Years',
    difficulty: 'EASY_MEDIUM',
    durationSeconds: 120,
    thumbnail: '/games/train-track-builder.svg',
    componentName: 'TRAIN_TRACK_BUILDER',
    gameType: 'REAL_TIME',
    templateCode: 'GT-TRAIN-TRACK',
    cognitiveSkill: 'Logical Thinking & Cause and Effect',
  },
  {
    name: 'Magic Train',
    slug: 'magic-train',
    description:
      'A real-time train-building assessment of pattern recognition and sequencing with visual, touch-first interactions.',
    category: 'Pattern Recognition & Sequencing',
    ageGroup: '4–5 Years',
    difficulty: 'EASY_MEDIUM',
    durationSeconds: 120,
    thumbnail: '/games/magic-train.svg',
    componentName: 'MAGIC_TRAIN',
    gameType: 'REAL_TIME',
    templateCode: 'GT-MAGIC-TRAIN',
    cognitiveSkill: 'Pattern Recognition & Sequencing',
  },
  {
    name: 'Rescue Mission',
    slug: 'rescue-mission',
    description:
      'A visual real-time assessment of problem solving and cognitive flexibility through friendly rescue situations.',
    category: 'Problem Solving & Cognitive Flexibility',
    ageGroup: '4–5 Years',
    difficulty: 'EASY_MEDIUM',
    durationSeconds: 120,
    thumbnail: '/games/rescue-mission.svg',
    componentName: 'RESCUE_MISSION',
    gameType: 'REAL_TIME',
    templateCode: 'GT-RESCUE-MISSION',
    cognitiveSkill: 'Problem Solving & Cognitive Flexibility',
  },
  {
    name: 'Parking Escape',
    slug: 'parking-escape',
    description:
      'A real-time parking assessment measuring strategic planning and spatial reasoning through direct vehicle movement.',
    category: 'Strategic Planning & Spatial Reasoning',
    ageGroup: '5–7 Years',
    difficulty: 'MEDIUM',
    durationSeconds: 120,
    thumbnail: '/games/parking-escape.svg',
    componentName: 'PARKING_ESCAPE',
    gameType: 'REAL_TIME',
    templateCode: 'GT-PARKING-ESCAPE',
    cognitiveSkill: 'Strategic Planning & Spatial Reasoning',
  },
  {
    name: 'Water Pipeline',
    slug: 'water-pipeline',
    description:
      'A direct-manipulation pipeline assessment measuring logical reasoning and problem solving through connected water routes.',
    category: 'Logical Reasoning & Problem Solving',
    ageGroup: '5–7 Years',
    difficulty: 'MEDIUM',
    durationSeconds: 120,
    thumbnail: '/games/water-pipeline.svg',
    componentName: 'WATER_PIPELINE',
    gameType: 'REAL_TIME',
    templateCode: 'GT-WATER-PIPELINE',
    cognitiveSkill: 'Logical Reasoning & Problem Solving',
  },
  {
    name: 'Ball Sort',
    slug: 'ball-sort',
    description:
      'An interactive sorting game assessing categorization, visual discrimination, and cognitive flexibility by organizing colored balls into containers.',
    category: 'Categorization & Cognitive Flexibility',
    ageGroup: '5–7 Years',
    difficulty: 'EASY',
    durationSeconds: 120,
    thumbnail: '/games/ball-sort.svg',
    componentName: 'BALL_SORT',
    gameType: 'REAL_TIME',
    templateCode: 'GT-BALL-SORT',
    cognitiveSkill: 'Categorization & Cognitive Flexibility',
  },
  {
    name: 'Red Light, Green Light',
    slug: 'red-light-green-light',
    description:
      'An interactive game assessing self-regulation, inhibitory control, and instruction-following by controlling movement in response to visual cues.',
    category: 'Self-Regulation & Inhibitory Control',
    ageGroup: '4–5 Years',
    difficulty: 'EASY',
    durationSeconds: 120,
    thumbnail: '/games/red-light-green-light.svg',
    componentName: 'RED_LIGHT_GREEN_LIGHT',
    gameType: 'REAL_TIME',
    templateCode: 'GT-RED-LIGHT-GREEN-LIGHT',
    cognitiveSkill: 'Self-Regulation & Inhibitory Control',
  },
  {
    name: 'Pattern Matrix',
    slug: 'pattern-matrix',
    description:
      'A visual memory assessment where students observe and recreate increasingly complex tile patterns.',
    category: 'Visual Memory & Pattern Recognition',
    ageGroup: '5–7 Years',
    difficulty: 'MEDIUM',
    durationSeconds: 120,
    thumbnail: '/games/pattern-matrix.svg',
    componentName: 'PATTERN_MATRIX',
    gameType: 'REAL_TIME',
    templateCode: 'GT-PATTERN-MATRIX',
    cognitiveSkill: 'Visual Memory, Attention & Spatial Recall',
  },
  {
    name: 'Catch the Target',
    slug: 'catch-the-target',
    description:
      'A Magic Garden assessment where children track falling objects, move a basket, catch the current target, and avoid distractors.',
    category: 'Visual Tracking & Hand-Eye Coordination',
    ageGroup: '5–7 Years',
    difficulty: 'PROGRESSIVE',
    durationSeconds: 120,
    thumbnail: '/games/catch-the-target.svg',
    componentName: 'CATCH_THE_TARGET',
    gameType: 'REAL_TIME',
    templateCode: 'GT-CATCH-THE-TARGET',
    cognitiveSkill: 'Visual Tracking',
  },
  {
    name: 'Mental Rotation',
    slug: 'mental-rotation',
    description:
      'A direct-manipulation spatial assessment where children rotate original geometric objects to match progressively more complex target orientations.',
    category: 'Spatial Visualization',
    ageGroup: '7–9 Years',
    difficulty: 'PROGRESSIVE',
    durationSeconds: 120,
    thumbnail: '/games/mental-rotation.svg',
    componentName: 'MENTAL_ROTATION',
    gameType: 'REAL_TIME',
    templateCode: 'GT-MENTAL-ROTATION',
    cognitiveSkill: 'Spatial Reasoning',
  },
  {
    name: 'Color Shift — Cognitive Flexibility Challenge',
    slug: 'color-shift',
    description:
      'A real-time arcade assessment where children move through a colorful arena, collect changing targets, avoid distractors, and adapt as visual rules shift.',
    category: 'Cognitive Flexibility & Attention',
    ageGroup: '7–9 Years',
    difficulty: 'PROGRESSIVE',
    durationSeconds: 120,
    thumbnail: '/games/color-shift.svg',
    componentName: 'COLOR_SHIFT',
    gameType: 'REAL_TIME',
    templateCode: 'GT-COLOR-SHIFT',
    cognitiveSkill: 'Cognitive Flexibility',
  },
  {
    name: 'Water Jugs',
    slug: 'water-jugs',
    description:
      'A visual real-time container puzzle that assesses planning, logical reasoning, and efficient problem solving through direct fill, empty, and pour interactions.',
    category: 'Logical Reasoning & Problem Solving',
    ageGroup: '7–9 Years',
    difficulty: 'PROGRESSIVE',
    durationSeconds: 120,
    thumbnail: '/games/water-jugs.svg',
    componentName: 'WATER_JUGS',
    gameType: 'REAL_TIME',
    templateCode: 'GT-WATER-JUGS',
    cognitiveSkill: 'Logical Reasoning',
  },
  {
    name: 'Tangram Builder',
    slug: 'tangram-builder',
    description:
      'A direct-manipulation spatial assessment where children drag, rotate, position, and combine geometric pieces to recreate original silhouettes.',
    category: 'Spatial Reasoning',
    ageGroup: '7–9 Years',
    difficulty: 'PROGRESSIVE',
    durationSeconds: 120,
    thumbnail: '/games/tangram-builder.svg',
    componentName: 'TANGRAM_BUILDER',
    gameType: 'REAL_TIME',
    templateCode: 'GT-TANGRAM-BUILDER',
    cognitiveSkill: 'Spatial Reasoning',
  },
  {
    name: 'Sokoban — Box Planning Challenge',
    slug: 'sokoban',
    description:
      'A visual real-time treasure delivery puzzle that assesses planning, spatial reasoning, sequencing, and efficient problem solving through direct movement and box pushing.',
    category: 'Planning & Problem Solving',
    ageGroup: '7–9 Years',
    difficulty: 'PROGRESSIVE',
    durationSeconds: 120,
    thumbnail: '/games/sokoban.svg',
    componentName: 'SOKOBAN',
    gameType: 'REAL_TIME',
    templateCode: 'GT-SOKOBAN',
    cognitiveSkill: 'Planning',
  },
  {
    name: 'Board Game Arena',
    slug: 'board-game-arena',
    description: 'An interactive real-time board game experience.',
    category: 'Board',
    ageGroup: '7–9 Years',
    difficulty: 'MEDIUM',
    durationSeconds: 900,
    thumbnail: '/games/board-game-arena.svg',
    componentName: 'BOARD_GAME',
    gameType: 'ASSESSMENT_ENGINE',
    templateCode: 'GT-BOARD',
    cognitiveSkill: 'Strategic Thinking',
  },
  {
    name: 'Bridge Builder',
    slug: 'bridge-builder',
    description: 'A hands-on building game with physics-based interactions.',
    category: 'Building',
    ageGroup: '9–11 Years',
    difficulty: 'MEDIUM',
    durationSeconds: 900,
    thumbnail: '/games/bridge-builder.svg',
    componentName: 'BUILDING_GAME',
    gameType: 'ASSESSMENT_ENGINE',
    templateCode: 'GT-BUILDING',
    cognitiveSkill: 'Spatial Reasoning',
  },
  {
    name: 'Factory Automation',
    slug: 'factory-automation',
    description: 'A real-time factory workflow and matching game.',
    category: 'Simulation',
    ageGroup: '11–13 Years',
    difficulty: 'MEDIUM',
    durationSeconds: 720,
    thumbnail: '/games/factory-automation.svg',
    componentName: 'MATCHING_GAME',
    gameType: 'ASSESSMENT_ENGINE',
    templateCode: 'GT-DRAGDROP',
    cognitiveSkill: 'Pattern Recognition',
  },
  {
    name: 'Fishing Master',
    slug: 'fishing-master',
    description: 'A responsive fishing game with live movement and timing.',
    category: 'Arcade',
    ageGroup: '5–7 Years',
    difficulty: 'MEDIUM',
    durationSeconds: 600,
    thumbnail: '/games/fishing-master.svg',
    componentName: 'FISHING_GAME',
    gameType: 'ASSESSMENT_ENGINE',
    templateCode: 'GT-FISHING',
    cognitiveSkill: 'Selective Attention',
  },
  {
    name: 'Follow the Lights',
    slug: 'follow-the-lights',
    description:
      'A real-time light sequence game with sound and touch interactions.',
    category: 'Memory',
    ageGroup: '3–4 Years',
    difficulty: 'EASY',
    durationSeconds: 120,
    thumbnail: '/games/follow-the-lights.svg',
    componentName: 'FOLLOW_THE_LIGHTS',
    gameType: 'REAL_TIME',
    templateCode: 'GT-MEMORY',
    cognitiveSkill: 'Working Memory',
  },
  {
    name: 'Math Racer',
    slug: 'math-racer',
    description: 'A live racing game with responsive steering and progression.',
    category: 'Racing',
    ageGroup: '7–9 Years',
    difficulty: 'MEDIUM',
    durationSeconds: 720,
    thumbnail: '/games/math-racer.svg',
    componentName: 'RACING_GAME',
    gameType: 'ASSESSMENT_ENGINE',
    templateCode: 'GT-RACING',
    cognitiveSkill: 'Numerical Fluency',
  },
  {
    name: 'Maze Dash',
    slug: 'maze-dash',
    description: 'A real-time maze navigation game.',
    category: 'Maze',
    ageGroup: '5–7 Years',
    difficulty: 'MEDIUM',
    durationSeconds: 900,
    thumbnail: '/games/maze-dash.svg',
    componentName: 'MAZE',
    gameType: 'ASSESSMENT_ENGINE',
    templateCode: 'GT-MAZE',
    cognitiveSkill: 'Planning',
  },
  {
    name: 'Robot Programming',
    slug: 'robot-programming',
    description:
      'A live logic game based on programmable movement and sequences.',
    category: 'Logic',
    ageGroup: '11–13 Years',
    difficulty: 'MEDIUM',
    durationSeconds: 900,
    thumbnail: '/games/robot-programming.svg',
    componentName: 'LOGIC_GAME',
    gameType: 'ASSESSMENT_ENGINE',
    templateCode: 'GT-LOGIC',
    cognitiveSkill: 'Logical Reasoning',
  },
  {
    name: 'Treasure Hunt Adventure',
    slug: 'treasure-hunt-adventure',
    description: 'An interactive treasure hunt with live exploration.',
    category: 'Adventure',
    ageGroup: '7–9 Years',
    difficulty: 'MEDIUM',
    durationSeconds: 900,
    thumbnail: '/games/treasure-hunt-adventure.svg',
    componentName: 'TREASURE_HUNT',
    gameType: 'ASSESSMENT_ENGINE',
    templateCode: 'GT-TREASURE',
    cognitiveSkill: 'Problem Solving',
  },
  {
    name: 'Sound Detective',
    slug: 'sound-detective',
    description:
      'An auditory recognition assessment game where children listen and identify matching objects or animals.',
    category: 'Auditory Recognition',
    ageGroup: '3–4 Years',
    difficulty: 'EASY',
    durationSeconds: 120,
    thumbnail: '/games/sound-detective.svg',
    componentName: 'SOUND_DETECTIVE',
    gameType: 'REAL_TIME',
    templateCode: 'GT-SOUND',
    cognitiveSkill: 'Auditory Recognition & Listening',
  },
  {
    name: 'Package Sorter',
    slug: 'package-sorter',
    description:
      'An engaging warehouse sorting assessment measuring organization, sorting accuracy, decision time, and decision-making skills.',
    category: 'Organization',
    ageGroup: '4–5 Years',
    difficulty: 'EASY_MEDIUM',
    durationSeconds: 120,
    thumbnail: '/games/package-sorter.svg',
    componentName: 'PACKAGE_SORTER',
    gameType: 'REAL_TIME',
    templateCode: 'GT-SORTER',
    cognitiveSkill: 'Organization & Decision Making',
  },
  {
    name: 'Air Hockey Challenge — Attention & Response Control',
    slug: 'air-hockey-challenge',
    description:
      'A continuous arcade air-hockey assessment where children track a moving puck, control a paddle, intercept returns, and adapt to changing trajectories.',
    category: 'Attention & Response Control',
    ageGroup: '9–11 Years',
    difficulty: 'PROGRESSIVE',
    durationSeconds: 120,
    thumbnail: '/games/air-hockey-challenge.svg',
    componentName: 'AIR_HOCKEY_CHALLENGE',
    gameType: 'REAL_TIME',
    templateCode: 'GT-AIR-HOCKEY',
    cognitiveSkill: 'Sustained Attention',
  },
  {
    name: 'Memory Market — Working Memory & Planning',
    slug: 'memory-market',
    description:
      'A continuous market simulation where children remember customer orders, navigate shelves, manage a basket, serve multiple customers, and adapt to market changes.',
    category: 'Executive Function & Planning',
    ageGroup: '9–11 Years',
    difficulty: 'PROGRESSIVE',
    durationSeconds: 120,
    thumbnail: '/games/memory-market.svg',
    componentName: 'MEMORY_MARKET',
    gameType: 'REAL_TIME',
    templateCode: 'GT-MEMORY-MARKET',
    cognitiveSkill: 'Working Memory',
  },
  {
    name: 'Rule Shift Challenge — Cognitive Flexibility & Inhibitory Control',
    slug: 'rule-shift-challenge',
    description:
      'A real-time sorting game measuring cognitive flexibility and inhibitory control where children sort moving objects based on rules that change unpredictably.',
    category: 'Executive Function',
    ageGroup: '9–11 Years',
    difficulty: 'PROGRESSIVE',
    durationSeconds: 120,
    thumbnail: '/games/rule-shift-challenge.svg',
    componentName: 'RULE_SHIFT_CHALLENGE',
    gameType: 'REAL_TIME',
    templateCode: 'GT-RULE-SHIFT',
    cognitiveSkill: 'Cognitive Flexibility',
  },
];

